[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
postcard = { version = "1.1.1", features = ["experimental-derive"] }
serde = { version = "1.0.215", features = ["derive"], default-features = false }
